name: BuildTest

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set permissions
      run: chmod -R 755 storage/* bootstrap/cache/
      
    - name: Copy .env.example
      run: cp .env.example .env
      
    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader
      
    - name: Generate application key
      run: php artisan key:generate --force
      
    - name: Install yarn dependencies
      run: yarn
      
    - name: Build production assets
      run: yarn build:production
