name: BuildTest

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set permissions
      run: chmod -R 755 storage/* bootstrap/cache/
      
    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader
      
    - name: Install yarn dependencies
      run: yarn

    - name: Rebuild the Panel frontend
      run: export NODE_OPTIONS=--openssl-legacy-provider\
      
    - name: Build production assets
      run: yarn build:production
